name: Build LaTeX document
on:
  push:
    tags:
      - "v*"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: 
      image: texlive/texlive:latest 
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - run: git config --system --add safe.directory /__w/thesis/thesis
      - name: Get previous tag name
        id: previous_tag
        env:
          ref: ${{ github.ref }}
        run: |
          output=$(python3 .github/git_tag.py ${ref}) 
          echo "TAGNAME=$output" >> $GITHUB_OUTPUT
      - name: compile
        env:
          tag: ${{ steps.previous_tag.outputs.TAGNAME }}
          ref: ${{ github.ref }}
        run: |
          bash  ${GITHUB_WORKSPACE}/.github/compile.sh ${ref} ${tag}
      - name: upload compiled document
        uses: softprops/action-gh-release@ 975c1b265e11dd76618af1c374e7981f9a6ff44a
        with:
          files: |
            build/*.pdf
